version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: irys-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: irys_confession_board
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - irys-network-prod
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: irys-backend-prod
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - DB_NAME=irys_confession_board
      - JWT_SECRET=${JWT_SECRET}
      - IRYS_PRIVATE_KEY=${IRYS_PRIVATE_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - ENVIRONMENT=production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-60}
      - RATE_LIMIT_PER_HOUR=${RATE_LIMIT_PER_HOUR:-1000}
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - irys-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: irys-frontend-prod
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=${FRONTEND_BACKEND_URL}
      - REACT_APP_API_URL=${FRONTEND_API_URL}
      - REACT_APP_WS_URL=${FRONTEND_WS_URL}
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_DEBUG=false
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - irys-network-prod
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: irys-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - irys-network-prod

volumes:
  mongodb_data:
    driver: local

networks:
  irys-network-prod:
    driver: bridge 